// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Order struct {
	ID          int32
	OrderNumber string
	Status      string
	UploadedAt  time.Time
	UserID      int32
}

type User struct {
	// ID записи
	ID int32
	// Логин
	Login string
	// Хэш-пароль
	PassHash string
}
