// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	ID          int32
	OrderNumber string
	Status      string
	UploadedAt  time.Time
	UserID      int32
	Accrual     sql.NullInt64
	Withdraw    sql.NullInt64
}

type User struct {
	// ID записи
	ID int32
	// Логин
	Login string
	// Хэш-пароль
	PassHash string
}
