// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAllWithdrawals(ctx context.Context, userID int32) ([]GetAllWithdrawalsRow, error)
	GetBalance(ctx context.Context, userID int32) (int64, error)
	GetOrdersByUsers(ctx context.Context, userID int32) ([]GetOrdersByUsersRow, error)
	GetOrdersForAccrual(ctx context.Context, arg GetOrdersForAccrualParams) ([]string, error)
	GetPassword(ctx context.Context, login string) ([]GetPasswordRow, error)
	GetUserIDByOrder(ctx context.Context, orderNumber string) (int32, error)
	GetWithdraws(ctx context.Context, userID int32) (int64, error)
	SaveOrder(ctx context.Context, arg SaveOrderParams) (int32, error)
	SaveUser(ctx context.Context, arg SaveUserParams) (int32, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int32, error)
	WithdrawDB(ctx context.Context, arg WithdrawDBParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
