// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, login, pass_hash FROM USERS
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Login, &i.PassHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUsers = `-- name: GetOrdersByUsers :many
SELECT order_number, status, uploaded_at, accrual FROM orders WHERE user_id = $1
`

type GetOrdersByUsersRow struct {
	OrderNumber string
	Status      string
	UploadedAt  time.Time
	Accrual     sql.NullInt32
}

func (q *Queries) GetOrdersByUsers(ctx context.Context, userID int32) ([]GetOrdersByUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUsers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUsersRow
	for rows.Next() {
		var i GetOrdersByUsersRow
		if err := rows.Scan(
			&i.OrderNumber,
			&i.Status,
			&i.UploadedAt,
			&i.Accrual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersForAccrual = `-- name: GetOrdersForAccrual :many
SELECT order_number FROM orders WHERE status = $1
order by uploaded_at
LIMIT $2
`

type GetOrdersForAccrualParams struct {
	Status string
	Limit  int32
}

func (q *Queries) GetOrdersForAccrual(ctx context.Context, arg GetOrdersForAccrualParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersForAccrual, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var order_number string
		if err := rows.Scan(&order_number); err != nil {
			return nil, err
		}
		items = append(items, order_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPassword = `-- name: GetPassword :many
SELECT pass_hash, id FROM USERS WHERE login = $1
`

type GetPasswordRow struct {
	PassHash string
	ID       int32
}

func (q *Queries) GetPassword(ctx context.Context, login string) ([]GetPasswordRow, error) {
	rows, err := q.db.QueryContext(ctx, getPassword, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPasswordRow
	for rows.Next() {
		var i GetPasswordRow
		if err := rows.Scan(&i.PassHash, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDByOrder = `-- name: GetUserIDByOrder :one
SELECT user_id FROM ORDERS WHERE order_number = $1
`

func (q *Queries) GetUserIDByOrder(ctx context.Context, orderNumber string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByOrder, orderNumber)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const saveOrder = `-- name: SaveOrder :one
INSERT INTO ORDERS(order_number, status, uploaded_at, user_id)
VALUES($1, $2, $3, $4)
RETURNING id
`

type SaveOrderParams struct {
	OrderNumber string
	Status      string
	UploadedAt  time.Time
	UserID      int32
}

func (q *Queries) SaveOrder(ctx context.Context, arg SaveOrderParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveOrder,
		arg.OrderNumber,
		arg.Status,
		arg.UploadedAt,
		arg.UserID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO USERS (login, pass_hash) VALUES ($1, $2)
RETURNING id
`

type SaveUserParams struct {
	Login    string
	PassHash string
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveUser, arg.Login, arg.PassHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}
