// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, login, pass_hash FROM USERS
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Login, &i.PassHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPassword = `-- name: GetPassword :many
SELECT pass_hash, id FROM USERS WHERE login = $1
`

type GetPasswordRow struct {
	PassHash string
	ID       int32
}

func (q *Queries) GetPassword(ctx context.Context, login string) ([]GetPasswordRow, error) {
	rows, err := q.db.QueryContext(ctx, getPassword, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPasswordRow
	for rows.Next() {
		var i GetPasswordRow
		if err := rows.Scan(&i.PassHash, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOrder = `-- name: SaveOrder :one
INSERT INTO ORDERS(order_number, status, uploaded_at)
VALUES($1, $2, $3)
RETURNING id
`

type SaveOrderParams struct {
	OrderNumber string
	Status      string
	UploadedAt  time.Time
}

func (q *Queries) SaveOrder(ctx context.Context, arg SaveOrderParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveOrder, arg.OrderNumber, arg.Status, arg.UploadedAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const saveUser = `-- name: SaveUser :one
INSERT INTO USERS (login, pass_hash) VALUES ($1, $2)
RETURNING id
`

type SaveUserParams struct {
	Login    string
	PassHash string
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, saveUser, arg.Login, arg.PassHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}
